export const ROLES = {
  ADMIN: 'admin',
  TRAINEE: 'trainee',
  GUEST: 'guest'
};


export const PERMISSIONS = {
  // Admin permissions
  MANAGE_PROMPTS: [ROLES.ADMIN],
  MANAGE_BATCHES: [ROLES.ADMIN], 
  MANAGE_SCENARIOS: [ROLES.ADMIN],
  VIEW_ALL_ANALYTICS: [ROLES.ADMIN],
  
  // Trainee permissions
  ACCESS_TRAINING: [ROLES.ADMIN, ROLES.TRAINEE],
  VIEW_PERFORMANCE: [ROLES.ADMIN, ROLES.TRAINEE],
  
  // Common permissions
  VIEW_WELCOME: [ROLES.ADMIN, ROLES.TRAINEE, ROLES.GUEST],
  ACCESS_SETTINGS: [ROLES.ADMIN, ROLES.TRAINEE],
  ACCESS_HELP: [ROLES.ADMIN, ROLES.TRAINEE, ROLES.GUEST]
};

export const ROUTE_PERMISSIONS = {
  '/welcome': PERMISSIONS.VIEW_WELCOME,
  '/dashboard': PERMISSIONS.MANAGE_BATCHES,
  '/prompts': PERMISSIONS.MANAGE_PROMPTS,
  '/prompts/create': PERMISSIONS.MANAGE_PROMPTS,
  '/prompts/:id': PERMISSIONS.MANAGE_PROMPTS,
  '/prompts/:id/edit': PERMISSIONS.MANAGE_PROMPTS,
  '/scenario-engines': PERMISSIONS.MANAGE_SCENARIOS,
  '/analytics': PERMISSIONS.VIEW_ALL_ANALYTICS,
  '/training-center': PERMISSIONS.ACCESS_TRAINING,
  '/training/:sessionId': PERMISSIONS.ACCESS_TRAINING,
  '/performance': PERMISSIONS.VIEW_PERFORMANCE,
  '/agent/:agentId': PERMISSIONS.VIEW_PERFORMANCE,
  '/settings': PERMISSIONS.ACCESS_SETTINGS,
  '/help': PERMISSIONS.ACCESS_HELP,
};
