
export const ROLES = {
  ADMIN: 'admin',
  TRAINEE: 'trainee',
  USER: 'user'
};

export const PERMISSIONS = {
  MANAGE_PROMPTS: [ROLES.ADMIN],
  MANAGE_BATCHES: [ROLES.ADMIN],
  MANAGE_SCENARIOS: [ROLES.ADMIN],
  VIEW_ALL_ANALYTICS: [ROLES.ADMIN],
  ACCESS_TRAINING: [ROLES.ADMIN, ROLES.TRAINEE],
  VIEW_PERFORMANCE: [ROLES.ADMIN, ROLES.TRAINEE],
  VIEW_WELCOME: [ROLES.ADMIN, ROLES.TRAINEE, ROLES.USER],
  ACCESS_SETTINGS: [ROLES.ADMIN, ROLES.TRAINEE],
  ACCESS_HELP: [ROLES.ADMIN, ROLES.TRAINEE, ROLES.USER]
};
